  
name: Commit to Review Branch
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: pull
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}


      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3 
      
   
  
